package initialize

import (
	"go.uber.org/zap"
	"gorm.io/gorm"
	"os"
	"yuyu/global"
	"yuyu/model/system"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.GvaConfig.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysUser{},       // 用户表
		system.JwtBlacklist{},  // 黑名单表 token失效管理
		system.SysAdvert{},     // 轮播图广告表
		system.SysCategory{},   // 商品分类表
		system.SysBrand{},      // 品牌表
		system.SysHealthNews{}, // 新闻资讯表
		system.SysFast{},       // 禁食水果表
		system.SysFastCate{},   // 禁食分类表
		system.SysAddress{},    // 收货地址表

		// 自动化模块表
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		global.GvaLog.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GvaLog.Info("register table success")
}
